### PR TITLE
Readme improvements

### PR DESCRIPTION
**Pull request by jacekk**
* Updated readme:
   * repo URL fixed,
   * added `.env` creation step (by copying example),
* Added bower to dev dependency, to not require its global presence.

### CODE REVIEW

**Comment by thetutlage** [comment]
Ohh this is for the old website, new one is here https://github.com/adonisjs/adonisjs.com.

The v3 -> v4 got bunch of stale repos, I will be cleaning them shortly

**Comment by jacekk** [comment]
Old or not, it does not change the fact that `adonisjs/adonis-documentation` should be runnable OOTB. And it is not without above changes.

P.S.
I confirm I got confused which docs project is for which version, and how to run/build/test them :)

**Comment by thetutlage** [comment]
Yeah but it does change the fact that no one will use this repo anymore and it will be deleted in next week or so

**Comment by jacekk** [comment]
Got it. So should I close this PR?

**Comment by thetutlage** [comment]
Yeah that makes sense 😄

**Pull request closed without merging**
